version: "3"
services:
  node:
    build:
      dockerfile: docker/Dockerfile
      context: ..
    image: react_http_starting/node
    container_name: react_http_starting
    ports:
      - "3000:3000"
    volumes:
      - ..:/var/www/react-http-starting
    networks:
      - react_http_starting
networks:
  react_http_starting:
    driver: bridge
      